# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --very-verbose --filter ZkTransactionEncoderTests;
           swift test --skip-build --very-verbose --filter EIP712EncoderTests --skip EIP712EncoderTests.testEncodeDomainMemberValues;
           swift test --skip-build --very-verbose --filter PrivateKeyEthSignerTests;
           swift test --skip-build --very-verbose --filter Transaction712Tests;
           swift test --skip-build --very-verbose --filter ContractDeployerTests;
           swift test --skip-build --very-verbose --filter EthereumKeystoreV3Tests
